### ISSUE TITLE
Admin Notice for Conflict with Future Discourse Update

### ISSUE THREAD

**Issue by cogdog** [weallwegot/discourse-social-links-clickable#14]
I got an admin notice on my site using this plugin today referencing an issue with future Discourse upgrades

https://meta.discourse.org/t/preparing-for-discourses-upgrade-to-ember-5/287211

The info I see in my console is

> l @ deprecated.js:54
> deprecated.js:54 [THEME 24 'discourse-social-links-clickable'] Deprecation notice: Defining connector classes via registerConnectorClass is deprecated. See https://meta.discourse.org/t/32727 for more modern patterns. [deprecation id: discourse.register-connector-class-legacy]
> l @ deprecated.js:54
> deprecated.js:54 [THEME 24 'discourse-social-links-clickable'] Deprecation notice: Defining connector classes via registerConnectorClass is deprecated. See https://meta.discourse.org/t/32727 for more modern patterns. [deprecation id: discourse.register-connector-class-legacy]
> l @ deprecated.js:54
> plugin-api.js:154 [THEME 24 'discourse-social-links-clickable'] To prevent errors in tests, add a `pluginId` key to your `modifyClass` call. This will ensure the modification is only applied once.
> je @ plugin-api.js:154

**Comment by culturerich** [comment]
Also getting this and noticed in addition it broke my Admin user pages (though not other users), only the very initial header displayed, no page content or admin menu or anything.

**Comment by msebald** [comment]
Same problem everywhere. See here for error message:

[https://meta.discourse.org/t/clickable-social-icon-links-on-profile/158136/59](https://meta.discourse.org/t/clickable-social-icon-links-on-profile/158136/59)

**Comment by valenzine** [comment]
Check out this merged PR!

https://github.com/weallwegot/discourse-social-links-clickable/pull/16
